### ISSUE TITLE
Graph Comparing

### ISSUE THREAD

**Issue by eduardomazolini** [vitorboccio/corona-stats#1]
Please create a graph comparing the progression, based on the first cases. So we will know how much more people need to take seriously.

Great job

**Comment by vitorboccio** [comment]
Hey @eduardomazolini I am not 100% sure if I understood what u meant on your request, anyhow, I added a new chart on the main dashboard. This chart has a history of the selected country for the past 10 days. It's still under development a dynamic time range, which means, you as a user will be able to choose if you wanna see the past 5, 10, 15, 20, 30 days for example.
Let me know if this is what u meant in your initial request.

**Comment by vitorboccio** [comment]
chart implemented.
